### ISSUE TITLE
Build error due to discarded-qualifiers

### ISSUE THREAD

**Issue by kiefernforst** [aws/aws-lc#3312]
I'm trying to build 864b432cd7bf8218289a14131e2bde817609e6d0 with gcc 15 (sic!), Arch-based repo, bare metal. There is an error caused by https://github.com/aws/aws-lc/pull/3291/changes

```
In file included from ./aws-lc/crypto/rand_extra/urandom.c:70:
./aws-lc/crypto/rand_extra/../internal.h: In function 'OPENSSL_memchr':
./aws-lc/crypto/rand_extra/../internal.h:939:10: error: return discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  939 |   return memchr(s, c, n);
      |          ^~~~~~
```

see https://github.com/hnakamur/aws-lc/blob/9978a847da19c1e3a471e26c8778bc83ffcfcf86/crypto/internal.h#L942

PS: Sorry, my fault. A full checkout on a sparse checkout does not update.

**Comment by justsmth** [comment]
Hello!  I believe this issue was resolved a few months ago on our mainline w/ PR:
* https://github.com/aws/aws-lc/pull/3008

> see https://github.com/hnakamur/aws-lc/blob/9978a847da19c1e3a471e26c8778bc83ffcfcf86/crypto/internal.h#L942

This link shows the corrected code -- which is different than the code shown by your compile error:
```
  return (void *)memchr(s, c, n);
```
-- versus -- 
```
  939 |   return memchr(s, c, n);
```

> There is an error caused by https://github.com/aws/aws-lc/pull/3291/changes

This fix was cherry-picked onto our latest FIPS branch in #3291. 

Based on the compile error, I think the build environment still has the older code. Perhaps the build environment is out of sync?  Please let us know if you continue seeing this error with the latest code. Thanks!
